/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AisShipTypeRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AisShipTypeRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for AisShipTypeRestDto
        //private AisShipTypeRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AisShipTypeRestDto
            //instance = new AisShipTypeRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AisShipTypeRestDto
        /// </summary>
        [Test]
        public void AisShipTypeRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AisShipTypeRestDto
            //Assert.IsInstanceOfType<AisShipTypeRestDto> (instance, "variable 'instance' is a AisShipTypeRestDto");
        }


        /// <summary>
        /// Test the property 'CategoryText'
        /// </summary>
        [Test]
        public void CategoryTextTest()
        {
            // TODO unit test for the property 'CategoryText'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'DetailText'
        /// </summary>
        [Test]
        public void DetailTextTest()
        {
            // TODO unit test for the property 'DetailText'
        }

    }

}
