/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing IffModeRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IffModeRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for IffModeRestDto
        //private IffModeRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IffModeRestDto
            //instance = new IffModeRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IffModeRestDto
        /// </summary>
        [Test]
        public void IffModeRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IffModeRestDto
            //Assert.IsInstanceOfType<IffModeRestDto> (instance, "variable 'instance' is a IffModeRestDto");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Validity'
        /// </summary>
        [Test]
        public void ValidityTest()
        {
            // TODO unit test for the property 'Validity'
        }

    }

}
