/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TrackRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TrackRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for TrackRestDto
        //private TrackRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrackRestDto
            //instance = new TrackRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrackRestDto
        /// </summary>
        [Test]
        public void TrackRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TrackRestDto
            //Assert.IsInstanceOfType<TrackRestDto> (instance, "variable 'instance' is a TrackRestDto");
        }


        /// <summary>
        /// Test the property 'Affiliation'
        /// </summary>
        [Test]
        public void AffiliationTest()
        {
            // TODO unit test for the property 'Affiliation'
        }
        /// <summary>
        /// Test the property 'AisHeading'
        /// </summary>
        [Test]
        public void AisHeadingTest()
        {
            // TODO unit test for the property 'AisHeading'
        }
        /// <summary>
        /// Test the property 'AisNavStatus'
        /// </summary>
        [Test]
        public void AisNavStatusTest()
        {
            // TODO unit test for the property 'AisNavStatus'
        }
        /// <summary>
        /// Test the property 'AisTurnRate'
        /// </summary>
        [Test]
        public void AisTurnRateTest()
        {
            // TODO unit test for the property 'AisTurnRate'
        }
        /// <summary>
        /// Test the property 'AisUpdateDelta'
        /// </summary>
        [Test]
        public void AisUpdateDeltaTest()
        {
            // TODO unit test for the property 'AisUpdateDelta'
        }
        /// <summary>
        /// Test the property 'Bearing'
        /// </summary>
        [Test]
        public void BearingTest()
        {
            // TODO unit test for the property 'Bearing'
        }
        /// <summary>
        /// Test the property 'Boarding'
        /// </summary>
        [Test]
        public void BoardingTest()
        {
            // TODO unit test for the property 'Boarding'
        }
        /// <summary>
        /// Test the property 'Classification'
        /// </summary>
        [Test]
        public void ClassificationTest()
        {
            // TODO unit test for the property 'Classification'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Iff'
        /// </summary>
        [Test]
        public void IffTest()
        {
            // TODO unit test for the property 'Iff'
        }
        /// <summary>
        /// Test the property 'IsSourceGtc'
        /// </summary>
        [Test]
        public void IsSourceGtcTest()
        {
            // TODO unit test for the property 'IsSourceGtc'
        }
        /// <summary>
        /// Test the property 'Kinematics'
        /// </summary>
        [Test]
        public void KinematicsTest()
        {
            // TODO unit test for the property 'Kinematics'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PosUncertainty'
        /// </summary>
        [Test]
        public void PosUncertaintyTest()
        {
            // TODO unit test for the property 'PosUncertainty'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Quality'
        /// </summary>
        [Test]
        public void QualityTest()
        {
            // TODO unit test for the property 'Quality'
        }
        /// <summary>
        /// Test the property 'Range'
        /// </summary>
        [Test]
        public void RangeTest()
        {
            // TODO unit test for the property 'Range'
        }
        /// <summary>
        /// Test the property 'SensorSrcs'
        /// </summary>
        [Test]
        public void SensorSrcsTest()
        {
            // TODO unit test for the property 'SensorSrcs'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'TrackIDsResetTime'
        /// </summary>
        [Test]
        public void TrackIDsResetTimeTest()
        {
            // TODO unit test for the property 'TrackIDsResetTime'
        }
        /// <summary>
        /// Test the property 'UpdatingSrc'
        /// </summary>
        [Test]
        public void UpdatingSrcTest()
        {
            // TODO unit test for the property 'UpdatingSrc'
        }

    }

}
