/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TrackBoardingRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TrackBoardingRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for TrackBoardingRestDto
        //private TrackBoardingRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrackBoardingRestDto
            //instance = new TrackBoardingRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrackBoardingRestDto
        /// </summary>
        [Test]
        public void TrackBoardingRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TrackBoardingRestDto
            //Assert.IsInstanceOfType<TrackBoardingRestDto> (instance, "variable 'instance' is a TrackBoardingRestDto");
        }


        /// <summary>
        /// Test the property 'Boarding'
        /// </summary>
        [Test]
        public void BoardingTest()
        {
            // TODO unit test for the property 'Boarding'
        }

    }

}
