/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TrackAffiliationRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TrackAffiliationRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for TrackAffiliationRestDto
        //private TrackAffiliationRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TrackAffiliationRestDto
            //instance = new TrackAffiliationRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TrackAffiliationRestDto
        /// </summary>
        [Test]
        public void TrackAffiliationRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TrackAffiliationRestDto
            //Assert.IsInstanceOfType<TrackAffiliationRestDto> (instance, "variable 'instance' is a TrackAffiliationRestDto");
        }


        /// <summary>
        /// Test the property 'Affiliation'
        /// </summary>
        [Test]
        public void AffiliationTest()
        {
            // TODO unit test for the property 'Affiliation'
        }

    }

}
