/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AlarmAnchorWatchInputRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlarmAnchorWatchInputRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for AlarmAnchorWatchInputRestDto
        //private AlarmAnchorWatchInputRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlarmAnchorWatchInputRestDto
            //instance = new AlarmAnchorWatchInputRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlarmAnchorWatchInputRestDto
        /// </summary>
        [Test]
        public void AlarmAnchorWatchInputRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlarmAnchorWatchInputRestDto
            //Assert.IsInstanceOfType<AlarmAnchorWatchInputRestDto> (instance, "variable 'instance' is a AlarmAnchorWatchInputRestDto");
        }


        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }

    }

}
