/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AlarmStateChangedRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlarmStateChangedRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for AlarmStateChangedRestDto
        //private AlarmStateChangedRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlarmStateChangedRestDto
            //instance = new AlarmStateChangedRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlarmStateChangedRestDto
        /// </summary>
        [Test]
        public void AlarmStateChangedRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlarmStateChangedRestDto
            //Assert.IsInstanceOfType<AlarmStateChangedRestDto> (instance, "variable 'instance' is a AlarmStateChangedRestDto");
        }


        /// <summary>
        /// Test the property 'AlarmId'
        /// </summary>
        [Test]
        public void AlarmIdTest()
        {
            // TODO unit test for the property 'AlarmId'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'TrackIds'
        /// </summary>
        [Test]
        public void TrackIdsTest()
        {
            // TODO unit test for the property 'TrackIds'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
