/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GraphicsRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GraphicsRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for GraphicsRestDto
        //private GraphicsRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GraphicsRestDto
            //instance = new GraphicsRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GraphicsRestDto
        /// </summary>
        [Test]
        public void GraphicsRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GraphicsRestDto
            //Assert.IsInstanceOfType<GraphicsRestDto> (instance, "variable 'instance' is a GraphicsRestDto");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'TotalItems'
        /// </summary>
        [Test]
        public void TotalItemsTest()
        {
            // TODO unit test for the property 'TotalItems'
        }

    }

}
