/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GraphicCreateInRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GraphicCreateInRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for GraphicCreateInRestDto
        //private GraphicCreateInRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GraphicCreateInRestDto
            //instance = new GraphicCreateInRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GraphicCreateInRestDto
        /// </summary>
        [Test]
        public void GraphicCreateInRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GraphicCreateInRestDto
            //Assert.IsInstanceOfType<GraphicCreateInRestDto> (instance, "variable 'instance' is a GraphicCreateInRestDto");
        }


        /// <summary>
        /// Test the property 'Circle'
        /// </summary>
        [Test]
        public void CircleTest()
        {
            // TODO unit test for the property 'Circle'
        }
        /// <summary>
        /// Test the property 'GraphicProcessingType'
        /// </summary>
        [Test]
        public void GraphicProcessingTypeTest()
        {
            // TODO unit test for the property 'GraphicProcessingType'
        }
        /// <summary>
        /// Test the property 'Polygon'
        /// </summary>
        [Test]
        public void PolygonTest()
        {
            // TODO unit test for the property 'Polygon'
        }

    }

}
