/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Graphic Circle
    /// </summary>
    [DataContract]
        public partial class GraphicCircleRestDto :  IEquatable<GraphicCircleRestDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GraphicCircleRestDto" /> class.
        /// </summary>
        /// <param name="center">center (required).</param>
        /// <param name="radius">Radius (in meters) from the center of a circle (required).</param>
        public GraphicCircleRestDto(GeoLatLonRestDto center = default(GeoLatLonRestDto), int? radius = default(int?))
        {
            // to ensure "center" is required (not null)
            if (center == null)
            {
                throw new InvalidDataException("center is a required property for GraphicCircleRestDto and cannot be null");
            }
            else
            {
                this.Center = center;
            }
            // to ensure "radius" is required (not null)
            if (radius == null)
            {
                throw new InvalidDataException("radius is a required property for GraphicCircleRestDto and cannot be null");
            }
            else
            {
                this.Radius = radius;
            }
        }
        
        /// <summary>
        /// Gets or Sets Center
        /// </summary>
        [DataMember(Name="center", EmitDefaultValue=false)]
        public GeoLatLonRestDto Center { get; set; }

        /// <summary>
        /// Radius (in meters) from the center of a circle
        /// </summary>
        /// <value>Radius (in meters) from the center of a circle</value>
        [DataMember(Name="radius", EmitDefaultValue=false)]
        public int? Radius { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GraphicCircleRestDto {\n");
            sb.Append("  Center: ").Append(Center).Append("\n");
            sb.Append("  Radius: ").Append(Radius).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GraphicCircleRestDto);
        }

        /// <summary>
        /// Returns true if GraphicCircleRestDto instances are equal
        /// </summary>
        /// <param name="input">Instance of GraphicCircleRestDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GraphicCircleRestDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Center == input.Center ||
                    (this.Center != null &&
                    this.Center.Equals(input.Center))
                ) && 
                (
                    this.Radius == input.Radius ||
                    (this.Radius != null &&
                    this.Radius.Equals(input.Radius))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Center != null)
                    hashCode = hashCode * 59 + this.Center.GetHashCode();
                if (this.Radius != null)
                    hashCode = hashCode * 59 + this.Radius.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
