/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CentroidsRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CentroidsRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for CentroidsRestDto
        //private CentroidsRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CentroidsRestDto
            //instance = new CentroidsRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CentroidsRestDto
        /// </summary>
        [Test]
        public void CentroidsRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CentroidsRestDto
            //Assert.IsInstanceOfType<CentroidsRestDto> (instance, "variable 'instance' is a CentroidsRestDto");
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'MetersPerRangeBin'
        /// </summary>
        [Test]
        public void MetersPerRangeBinTest()
        {
            // TODO unit test for the property 'MetersPerRangeBin'
        }
        /// <summary>
        /// Test the property 'NotHeartbeating'
        /// </summary>
        [Test]
        public void NotHeartbeatingTest()
        {
            // TODO unit test for the property 'NotHeartbeating'
        }
        /// <summary>
        /// Test the property 'NumItems'
        /// </summary>
        [Test]
        public void NumItemsTest()
        {
            // TODO unit test for the property 'NumItems'
        }
        /// <summary>
        /// Test the property 'PosTime'
        /// </summary>
        [Test]
        public void PosTimeTest()
        {
            // TODO unit test for the property 'PosTime'
        }
        /// <summary>
        /// Test the property 'RadarLat'
        /// </summary>
        [Test]
        public void RadarLatTest()
        {
            // TODO unit test for the property 'RadarLat'
        }
        /// <summary>
        /// Test the property 'RadarLon'
        /// </summary>
        [Test]
        public void RadarLonTest()
        {
            // TODO unit test for the property 'RadarLon'
        }
        /// <summary>
        /// Test the property 'Rp'
        /// </summary>
        [Test]
        public void RpTest()
        {
            // TODO unit test for the property 'Rp'
        }
        /// <summary>
        /// Test the property 'Ws'
        /// </summary>
        [Test]
        public void WsTest()
        {
            // TODO unit test for the property 'Ws'
        }

    }

}
