/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CameraStationRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CameraStationRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for CameraStationRestDto
        //private CameraStationRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CameraStationRestDto
            //instance = new CameraStationRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CameraStationRestDto
        /// </summary>
        [Test]
        public void CameraStationRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CameraStationRestDto
            //Assert.IsInstanceOfType<CameraStationRestDto> (instance, "variable 'instance' is a CameraStationRestDto");
        }


        /// <summary>
        /// Test the property 'CameraServices'
        /// </summary>
        [Test]
        public void CameraServicesTest()
        {
            // TODO unit test for the property 'CameraServices'
        }
        /// <summary>
        /// Test the property 'ReportedTime'
        /// </summary>
        [Test]
        public void ReportedTimeTest()
        {
            // TODO unit test for the property 'ReportedTime'
        }

    }

}
