/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RPStationRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RPStationRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for RPStationRestDto
        //private RPStationRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RPStationRestDto
            //instance = new RPStationRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RPStationRestDto
        /// </summary>
        [Test]
        public void RPStationRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RPStationRestDto
            //Assert.IsInstanceOfType<RPStationRestDto> (instance, "variable 'instance' is a RPStationRestDto");
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'NavService'
        /// </summary>
        [Test]
        public void NavServiceTest()
        {
            // TODO unit test for the property 'NavService'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'RadarService'
        /// </summary>
        [Test]
        public void RadarServiceTest()
        {
            // TODO unit test for the property 'RadarService'
        }
        /// <summary>
        /// Test the property 'ReportedTime'
        /// </summary>
        [Test]
        public void ReportedTimeTest()
        {
            // TODO unit test for the property 'ReportedTime'
        }
        /// <summary>
        /// Test the property 'RpNum'
        /// </summary>
        [Test]
        public void RpNumTest()
        {
            // TODO unit test for the property 'RpNum'
        }
        /// <summary>
        /// Test the property 'StationName'
        /// </summary>
        [Test]
        public void StationNameTest()
        {
            // TODO unit test for the property 'StationName'
        }
        /// <summary>
        /// Test the property 'TrackerService'
        /// </summary>
        [Test]
        public void TrackerServiceTest()
        {
            // TODO unit test for the property 'TrackerService'
        }

    }

}
