/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing F21x7StatusTypeRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class F21x7StatusTypeRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for F21x7StatusTypeRestDto
        //private F21x7StatusTypeRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of F21x7StatusTypeRestDto
            //instance = new F21x7StatusTypeRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of F21x7StatusTypeRestDto
        /// </summary>
        [Test]
        public void F21x7StatusTypeRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" F21x7StatusTypeRestDto
            //Assert.IsInstanceOfType<F21x7StatusTypeRestDto> (instance, "variable 'instance' is a F21x7StatusTypeRestDto");
        }


        /// <summary>
        /// Test the property 'MagnetronHeaterStatus'
        /// </summary>
        [Test]
        public void MagnetronHeaterStatusTest()
        {
            // TODO unit test for the property 'MagnetronHeaterStatus'
        }
        /// <summary>
        /// Test the property 'Minus12vStatus'
        /// </summary>
        [Test]
        public void Minus12vStatusTest()
        {
            // TODO unit test for the property 'Minus12vStatus'
        }
        /// <summary>
        /// Test the property 'Plus12vStatus'
        /// </summary>
        [Test]
        public void Plus12vStatusTest()
        {
            // TODO unit test for the property 'Plus12vStatus'
        }
        /// <summary>
        /// Test the property 'Plus32vStatus'
        /// </summary>
        [Test]
        public void Plus32vStatusTest()
        {
            // TODO unit test for the property 'Plus32vStatus'
        }
        /// <summary>
        /// Test the property 'Plus5vStatus'
        /// </summary>
        [Test]
        public void Plus5vStatusTest()
        {
            // TODO unit test for the property 'Plus5vStatus'
        }
        /// <summary>
        /// Test the property 'RadarTemperature'
        /// </summary>
        [Test]
        public void RadarTemperatureTest()
        {
            // TODO unit test for the property 'RadarTemperature'
        }
        /// <summary>
        /// Test the property 'TransmitHvStatus'
        /// </summary>
        [Test]
        public void TransmitHvStatusTest()
        {
            // TODO unit test for the property 'TransmitHvStatus'
        }

    }

}
