/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FilterRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FilterRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for FilterRestDto
        //private FilterRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FilterRestDto
            //instance = new FilterRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FilterRestDto
        /// </summary>
        [Test]
        public void FilterRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FilterRestDto
            //Assert.IsInstanceOfType<FilterRestDto> (instance, "variable 'instance' is a FilterRestDto");
        }


        /// <summary>
        /// Test the property 'ClutterMode'
        /// </summary>
        [Test]
        public void ClutterModeTest()
        {
            // TODO unit test for the property 'ClutterMode'
        }
        /// <summary>
        /// Test the property 'GainControl'
        /// </summary>
        [Test]
        public void GainControlTest()
        {
            // TODO unit test for the property 'GainControl'
        }
        /// <summary>
        /// Test the property 'IrControl'
        /// </summary>
        [Test]
        public void IrControlTest()
        {
            // TODO unit test for the property 'IrControl'
        }
        /// <summary>
        /// Test the property 'RainControl'
        /// </summary>
        [Test]
        public void RainControlTest()
        {
            // TODO unit test for the property 'RainControl'
        }
        /// <summary>
        /// Test the property 'SeaControl'
        /// </summary>
        [Test]
        public void SeaControlTest()
        {
            // TODO unit test for the property 'SeaControl'
        }

    }

}
