/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RadarControlRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RadarControlRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for RadarControlRestDto
        //private RadarControlRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RadarControlRestDto
            //instance = new RadarControlRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RadarControlRestDto
        /// </summary>
        [Test]
        public void RadarControlRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RadarControlRestDto
            //Assert.IsInstanceOfType<RadarControlRestDto> (instance, "variable 'instance' is a RadarControlRestDto");
        }


        /// <summary>
        /// Test the property 'ClutterMode'
        /// </summary>
        [Test]
        public void ClutterModeTest()
        {
            // TODO unit test for the property 'ClutterMode'
        }
        /// <summary>
        /// Test the property 'Controller'
        /// </summary>
        [Test]
        public void ControllerTest()
        {
            // TODO unit test for the property 'Controller'
        }
        /// <summary>
        /// Test the property 'ControllerName'
        /// </summary>
        [Test]
        public void ControllerNameTest()
        {
            // TODO unit test for the property 'ControllerName'
        }
        /// <summary>
        /// Test the property 'GainControl'
        /// </summary>
        [Test]
        public void GainControlTest()
        {
            // TODO unit test for the property 'GainControl'
        }
        /// <summary>
        /// Test the property 'IrControl'
        /// </summary>
        [Test]
        public void IrControlTest()
        {
            // TODO unit test for the property 'IrControl'
        }
        /// <summary>
        /// Test the property 'IsAdjunctRp'
        /// </summary>
        [Test]
        public void IsAdjunctRpTest()
        {
            // TODO unit test for the property 'IsAdjunctRp'
        }
        /// <summary>
        /// Test the property 'IsNotUpdating'
        /// </summary>
        [Test]
        public void IsNotUpdatingTest()
        {
            // TODO unit test for the property 'IsNotUpdating'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'RadarMode'
        /// </summary>
        [Test]
        public void RadarModeTest()
        {
            // TODO unit test for the property 'RadarMode'
        }
        /// <summary>
        /// Test the property 'RadarState'
        /// </summary>
        [Test]
        public void RadarStateTest()
        {
            // TODO unit test for the property 'RadarState'
        }
        /// <summary>
        /// Test the property 'RainControl'
        /// </summary>
        [Test]
        public void RainControlTest()
        {
            // TODO unit test for the property 'RainControl'
        }
        /// <summary>
        /// Test the property 'RangeScale'
        /// </summary>
        [Test]
        public void RangeScaleTest()
        {
            // TODO unit test for the property 'RangeScale'
        }
        /// <summary>
        /// Test the property 'RpNum'
        /// </summary>
        [Test]
        public void RpNumTest()
        {
            // TODO unit test for the property 'RpNum'
        }
        /// <summary>
        /// Test the property 'SeaControl'
        /// </summary>
        [Test]
        public void SeaControlTest()
        {
            // TODO unit test for the property 'SeaControl'
        }
        /// <summary>
        /// Test the property 'TermaProfile'
        /// </summary>
        [Test]
        public void TermaProfileTest()
        {
            // TODO unit test for the property 'TermaProfile'
        }

    }

}
