/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RadarTermaBiteMRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RadarTermaBiteMRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for RadarTermaBiteMRestDto
        //private RadarTermaBiteMRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RadarTermaBiteMRestDto
            //instance = new RadarTermaBiteMRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RadarTermaBiteMRestDto
        /// </summary>
        [Test]
        public void RadarTermaBiteMRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RadarTermaBiteMRestDto
            //Assert.IsInstanceOfType<RadarTermaBiteMRestDto> (instance, "variable 'instance' is a RadarTermaBiteMRestDto");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ErrorOrWarnValue'
        /// </summary>
        [Test]
        public void ErrorOrWarnValueTest()
        {
            // TODO unit test for the property 'ErrorOrWarnValue'
        }
        /// <summary>
        /// Test the property 'FloatValue'
        /// </summary>
        [Test]
        public void FloatValueTest()
        {
            // TODO unit test for the property 'FloatValue'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RpTime'
        /// </summary>
        [Test]
        public void RpTimeTest()
        {
            // TODO unit test for the property 'RpTime'
        }
        /// <summary>
        /// Test the property 'TermaTime'
        /// </summary>
        [Test]
        public void TermaTimeTest()
        {
            // TODO unit test for the property 'TermaTime'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
