/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TermaProfileRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TermaProfileRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for TermaProfileRestDto
        //private TermaProfileRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TermaProfileRestDto
            //instance = new TermaProfileRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TermaProfileRestDto
        /// </summary>
        [Test]
        public void TermaProfileRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TermaProfileRestDto
            //Assert.IsInstanceOfType<TermaProfileRestDto> (instance, "variable 'instance' is a TermaProfileRestDto");
        }


        /// <summary>
        /// Test the property 'TermaProfile'
        /// </summary>
        [Test]
        public void TermaProfileTest()
        {
            // TODO unit test for the property 'TermaProfile'
        }

    }

}
