/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// DisplayStationRestDto
    /// </summary>
    [DataContract]
        public partial class DisplayStationRestDto :  IEquatable<DisplayStationRestDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisplayStationRestDto" /> class.
        /// </summary>
        /// <param name="count">Running sequence counter of heartbeat messages received for the Display Station. Available with expand&#x3D;detail.</param>
        /// <param name="reportedTime">reportedTime.</param>
        /// <param name="stationName">Name of the Display Station (required).</param>
        public DisplayStationRestDto(int? count = default(int?), ReportedTimeRestDto reportedTime = default(ReportedTimeRestDto), string stationName = default(string))
        {
            // to ensure "stationName" is required (not null)
            if (stationName == null)
            {
                throw new InvalidDataException("stationName is a required property for DisplayStationRestDto and cannot be null");
            }
            else
            {
                this.StationName = stationName;
            }
            this.Count = count;
            this.ReportedTime = reportedTime;
        }
        
        /// <summary>
        /// Running sequence counter of heartbeat messages received for the Display Station. Available with expand&#x3D;detail
        /// </summary>
        /// <value>Running sequence counter of heartbeat messages received for the Display Station. Available with expand&#x3D;detail</value>
        [DataMember(Name="count", EmitDefaultValue=false)]
        public int? Count { get; set; }

        /// <summary>
        /// Gets or Sets ReportedTime
        /// </summary>
        [DataMember(Name="reportedTime", EmitDefaultValue=false)]
        public ReportedTimeRestDto ReportedTime { get; set; }

        /// <summary>
        /// Name of the Display Station
        /// </summary>
        /// <value>Name of the Display Station</value>
        [DataMember(Name="stationName", EmitDefaultValue=false)]
        public string StationName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DisplayStationRestDto {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  ReportedTime: ").Append(ReportedTime).Append("\n");
            sb.Append("  StationName: ").Append(StationName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DisplayStationRestDto);
        }

        /// <summary>
        /// Returns true if DisplayStationRestDto instances are equal
        /// </summary>
        /// <param name="input">Instance of DisplayStationRestDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DisplayStationRestDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Count == input.Count ||
                    (this.Count != null &&
                    this.Count.Equals(input.Count))
                ) && 
                (
                    this.ReportedTime == input.ReportedTime ||
                    (this.ReportedTime != null &&
                    this.ReportedTime.Equals(input.ReportedTime))
                ) && 
                (
                    this.StationName == input.StationName ||
                    (this.StationName != null &&
                    this.StationName.Equals(input.StationName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Count != null)
                    hashCode = hashCode * 59 + this.Count.GetHashCode();
                if (this.ReportedTime != null)
                    hashCode = hashCode * 59 + this.ReportedTime.GetHashCode();
                if (this.StationName != null)
                    hashCode = hashCode * 59 + this.StationName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
