/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AlarmCpaInputRestDto
    /// </summary>
    [DataContract]
        public partial class AlarmCpaInputRestDto :  IEquatable<AlarmCpaInputRestDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlarmCpaInputRestDto" /> class.
        /// </summary>
        /// <param name="distance">[1 and greater]: Distance which along with time defines the CPA (Closest Point of Approach) alarm (in meters).</param>
        /// <param name="time">[1 and greater]: Time which along with distance defines the CPA (Closest Point of Approach) alarm (in seconds).</param>
        public AlarmCpaInputRestDto(int? distance = default(int?), int? time = default(int?))
        {
            this.Distance = distance;
            this.Time = time;
        }
        
        /// <summary>
        /// [1 and greater]: Distance which along with time defines the CPA (Closest Point of Approach) alarm (in meters)
        /// </summary>
        /// <value>[1 and greater]: Distance which along with time defines the CPA (Closest Point of Approach) alarm (in meters)</value>
        [DataMember(Name="distance", EmitDefaultValue=false)]
        public int? Distance { get; set; }

        /// <summary>
        /// [1 and greater]: Time which along with distance defines the CPA (Closest Point of Approach) alarm (in seconds)
        /// </summary>
        /// <value>[1 and greater]: Time which along with distance defines the CPA (Closest Point of Approach) alarm (in seconds)</value>
        [DataMember(Name="time", EmitDefaultValue=false)]
        public int? Time { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlarmCpaInputRestDto {\n");
            sb.Append("  Distance: ").Append(Distance).Append("\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlarmCpaInputRestDto);
        }

        /// <summary>
        /// Returns true if AlarmCpaInputRestDto instances are equal
        /// </summary>
        /// <param name="input">Instance of AlarmCpaInputRestDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlarmCpaInputRestDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Distance == input.Distance ||
                    (this.Distance != null &&
                    this.Distance.Equals(input.Distance))
                ) && 
                (
                    this.Time == input.Time ||
                    (this.Time != null &&
                    this.Time.Equals(input.Time))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Distance != null)
                    hashCode = hashCode * 59 + this.Distance.GetHashCode();
                if (this.Time != null)
                    hashCode = hashCode * 59 + this.Time.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
