/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AlertRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for AlertRestDto
        //private AlertRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertRestDto
            //instance = new AlertRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertRestDto
        /// </summary>
        [Test]
        public void AlertRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertRestDto
            //Assert.IsInstanceOfType<AlertRestDto> (instance, "variable 'instance' is a AlertRestDto");
        }


        /// <summary>
        /// Test the property 'AckState'
        /// </summary>
        [Test]
        public void AckStateTest()
        {
            // TODO unit test for the property 'AckState'
        }
        /// <summary>
        /// Test the property 'ActiveState'
        /// </summary>
        [Test]
        public void ActiveStateTest()
        {
            // TODO unit test for the property 'ActiveState'
        }
        /// <summary>
        /// Test the property 'AlertInternalId'
        /// </summary>
        [Test]
        public void AlertInternalIdTest()
        {
            // TODO unit test for the property 'AlertInternalId'
        }
        /// <summary>
        /// Test the property 'AlertText'
        /// </summary>
        [Test]
        public void AlertTextTest()
        {
            // TODO unit test for the property 'AlertText'
        }
        /// <summary>
        /// Test the property 'DetailedAlertText'
        /// </summary>
        [Test]
        public void DetailedAlertTextTest()
        {
            // TODO unit test for the property 'DetailedAlertText'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsMarkedForDeletion'
        /// </summary>
        [Test]
        public void IsMarkedForDeletionTest()
        {
            // TODO unit test for the property 'IsMarkedForDeletion'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

    }

}
