/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Ship
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShipTests
    {
        // TODO uncomment below to declare an instance variable for Ship
        //private Ship instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Ship
            //instance = new Ship();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Ship
        /// </summary>
        [Test]
        public void ShipInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Ship
            //Assert.IsInstanceOfType<Ship> (instance, "variable 'instance' is a Ship");
        }


        /// <summary>
        /// Test the property 'AisName'
        /// </summary>
        [Test]
        public void AisNameTest()
        {
            // TODO unit test for the property 'AisName'
        }
        /// <summary>
        /// Test the property 'CallSign'
        /// </summary>
        [Test]
        public void CallSignTest()
        {
            // TODO unit test for the property 'CallSign'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'FlagUrl'
        /// </summary>
        [Test]
        public void FlagUrlTest()
        {
            // TODO unit test for the property 'FlagUrl'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Test]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ImoNumber'
        /// </summary>
        [Test]
        public void ImoNumberTest()
        {
            // TODO unit test for the property 'ImoNumber'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'MmsiNumber'
        /// </summary>
        [Test]
        public void MmsiNumberTest()
        {
            // TODO unit test for the property 'MmsiNumber'
        }
        /// <summary>
        /// Test the property 'ShipDetail'
        /// </summary>
        [Test]
        public void ShipDetailTest()
        {
            // TODO unit test for the property 'ShipDetail'
        }
        /// <summary>
        /// Test the property 'SourceType'
        /// </summary>
        [Test]
        public void SourceTypeTest()
        {
            // TODO unit test for the property 'SourceType'
        }
        /// <summary>
        /// Test the property 'ThumbnailUrl'
        /// </summary>
        [Test]
        public void ThumbnailUrlTest()
        {
            // TODO unit test for the property 'ThumbnailUrl'
        }

    }

}
