/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ShipsRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ShipsRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for ShipsRestDto
        //private ShipsRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ShipsRestDto
            //instance = new ShipsRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ShipsRestDto
        /// </summary>
        [Test]
        public void ShipsRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShipsRestDto
            //Assert.IsInstanceOfType<ShipsRestDto> (instance, "variable 'instance' is a ShipsRestDto");
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'Ships'
        /// </summary>
        [Test]
        public void ShipsTest()
        {
            // TODO unit test for the property 'Ships'
        }
        /// <summary>
        /// Test the property 'TotalItems'
        /// </summary>
        [Test]
        public void TotalItemsTest()
        {
            // TODO unit test for the property 'TotalItems'
        }

    }

}
