/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Geophysical location
    /// </summary>
    [DataContract]
        public partial class GeoPosRestDto :  IEquatable<GeoPosRestDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeoPosRestDto" /> class.
        /// </summary>
        /// <param name="altitude">Height of the object above sea level (meters).</param>
        /// <param name="latitude">[-90 to +90]: Latitude of the object (Decimal Degrees, North Positive/South Negative) (required).</param>
        /// <param name="longitude">[-180 to +180]: Longitude of the object (Decimal Degrees, East Positive/West Negative) (required).</param>
        public GeoPosRestDto(double? altitude = default(double?), double? latitude = default(double?), double? longitude = default(double?))
        {
            // to ensure "latitude" is required (not null)
            if (latitude == null)
            {
                throw new InvalidDataException("latitude is a required property for GeoPosRestDto and cannot be null");
            }
            else
            {
                this.Latitude = latitude;
            }
            // to ensure "longitude" is required (not null)
            if (longitude == null)
            {
                throw new InvalidDataException("longitude is a required property for GeoPosRestDto and cannot be null");
            }
            else
            {
                this.Longitude = longitude;
            }
            this.Altitude = altitude;
        }
        
        /// <summary>
        /// Height of the object above sea level (meters)
        /// </summary>
        /// <value>Height of the object above sea level (meters)</value>
        [DataMember(Name="altitude", EmitDefaultValue=false)]
        public double? Altitude { get; set; }

        /// <summary>
        /// [-90 to +90]: Latitude of the object (Decimal Degrees, North Positive/South Negative)
        /// </summary>
        /// <value>[-90 to +90]: Latitude of the object (Decimal Degrees, North Positive/South Negative)</value>
        [DataMember(Name="latitude", EmitDefaultValue=false)]
        public double? Latitude { get; set; }

        /// <summary>
        /// [-180 to +180]: Longitude of the object (Decimal Degrees, East Positive/West Negative)
        /// </summary>
        /// <value>[-180 to +180]: Longitude of the object (Decimal Degrees, East Positive/West Negative)</value>
        [DataMember(Name="longitude", EmitDefaultValue=false)]
        public double? Longitude { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GeoPosRestDto {\n");
            sb.Append("  Altitude: ").Append(Altitude).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GeoPosRestDto);
        }

        /// <summary>
        /// Returns true if GeoPosRestDto instances are equal
        /// </summary>
        /// <param name="input">Instance of GeoPosRestDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GeoPosRestDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Altitude == input.Altitude ||
                    (this.Altitude != null &&
                    this.Altitude.Equals(input.Altitude))
                ) && 
                (
                    this.Latitude == input.Latitude ||
                    (this.Latitude != null &&
                    this.Latitude.Equals(input.Latitude))
                ) && 
                (
                    this.Longitude == input.Longitude ||
                    (this.Longitude != null &&
                    this.Longitude.Equals(input.Longitude))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Altitude != null)
                    hashCode = hashCode * 59 + this.Altitude.GetHashCode();
                if (this.Latitude != null)
                    hashCode = hashCode * 59 + this.Latitude.GetHashCode();
                if (this.Longitude != null)
                    hashCode = hashCode * 59 + this.Longitude.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
