/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CameraCommandPanTiltZoomRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CameraCommandPanTiltZoomRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for CameraCommandPanTiltZoomRestDto
        //private CameraCommandPanTiltZoomRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CameraCommandPanTiltZoomRestDto
            //instance = new CameraCommandPanTiltZoomRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CameraCommandPanTiltZoomRestDto
        /// </summary>
        [Test]
        public void CameraCommandPanTiltZoomRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CameraCommandPanTiltZoomRestDto
            //Assert.IsInstanceOfType<CameraCommandPanTiltZoomRestDto> (instance, "variable 'instance' is a CameraCommandPanTiltZoomRestDto");
        }


        /// <summary>
        /// Test the property 'Pan'
        /// </summary>
        [Test]
        public void PanTest()
        {
            // TODO unit test for the property 'Pan'
        }
        /// <summary>
        /// Test the property 'Tilt'
        /// </summary>
        [Test]
        public void TiltTest()
        {
            // TODO unit test for the property 'Tilt'
        }
        /// <summary>
        /// Test the property 'Zoom'
        /// </summary>
        [Test]
        public void ZoomTest()
        {
            // TODO unit test for the property 'Zoom'
        }

    }

}
