/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CameraCommandPelcoRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CameraCommandPelcoRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for CameraCommandPelcoRestDto
        //private CameraCommandPelcoRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CameraCommandPelcoRestDto
            //instance = new CameraCommandPelcoRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CameraCommandPelcoRestDto
        /// </summary>
        [Test]
        public void CameraCommandPelcoRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CameraCommandPelcoRestDto
            //Assert.IsInstanceOfType<CameraCommandPelcoRestDto> (instance, "variable 'instance' is a CameraCommandPelcoRestDto");
        }


        /// <summary>
        /// Test the property 'Command1'
        /// </summary>
        [Test]
        public void Command1Test()
        {
            // TODO unit test for the property 'Command1'
        }
        /// <summary>
        /// Test the property 'Command2'
        /// </summary>
        [Test]
        public void Command2Test()
        {
            // TODO unit test for the property 'Command2'
        }
        /// <summary>
        /// Test the property 'Data1'
        /// </summary>
        [Test]
        public void Data1Test()
        {
            // TODO unit test for the property 'Data1'
        }
        /// <summary>
        /// Test the property 'Data2'
        /// </summary>
        [Test]
        public void Data2Test()
        {
            // TODO unit test for the property 'Data2'
        }

    }

}
