/* 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CameraCommandAssignTrackRestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CameraCommandAssignTrackRestDtoTests
    {
        // TODO uncomment below to declare an instance variable for CameraCommandAssignTrackRestDto
        //private CameraCommandAssignTrackRestDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CameraCommandAssignTrackRestDto
            //instance = new CameraCommandAssignTrackRestDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CameraCommandAssignTrackRestDto
        /// </summary>
        [Test]
        public void CameraCommandAssignTrackRestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CameraCommandAssignTrackRestDto
            //Assert.IsInstanceOfType<CameraCommandAssignTrackRestDto> (instance, "variable 'instance' is a CameraCommandAssignTrackRestDto");
        }


        /// <summary>
        /// Test the property 'TrackToAssign'
        /// </summary>
        [Test]
        public void TrackToAssignTest()
        {
            // TODO unit test for the property 'TrackToAssign'
        }

    }

}
